#!/bin/bash
#PBS -P xr60
#PBS -l walltime=00:10:00
#PBS -l ncpus=96
#PBS -l mem=190gb
#PBS -l software=qe
#PBS -l wd

module load openmpi/4.1.2

module load qe/7.0

export OMP_NUM_THREADS=4

mpirun -map-by ppr:3:numa:PE=4 -x OMP_NUM_THREADS=4 -display-map pw.x -npool 3 -ndiag 1 -inp CeO2.in > CeO2.out


#mpirun pw.x -npool 3 -ndiag 1 -inp CeO2.in > CeO2.out
